version: "3"

networks:
  loki:

services:
  loki:
    image: grafana/loki:2.8.7
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.8.7
    volumes:
      - /var/log:/var/log
      - $PWD/promtail.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    ports:
      - "9080:9080"
    networks:
      - loki

  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy 
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - loki
    
  # Using docker loki log driver to send the logs
  # docker plugin install grafana/loki-docker-driver:2.9.1 --alias loki --grant-all-permissions
  # docker plugin list
  # docker plugin enable loki
  # docker plugin disable loki
  # docker plugin upgrade loki
  # https://github.com/grafana/loki/tree/v2.9.3/clients/cmd/docker-driver
  log-generator:
    image: alpine
    command:
      - "/bin/sh"
      - "-c"
      - "while [ 1 ]; do echo log message at `date '+%s'`; sleep 5; done"
    networks:
      - loki 
    volumes:
      - $PWD/log-generator.sh:/log-generator.sh
    logging:
      driver: loki
      options:
        loki-url: http://localhost:3100/loki/api/v1/push
        loki-retries: "5"
        loki-batch-size: "5"
        max-size: 10m
        max-file: 3
        loki-pipeline-stages: |
          - regex:
              expression: '.* message at (?P<msg>\w+)'
          - labels:
              msg:
              network: devnet